baseURL = 'https://synergyvr.org/mgo/'
CanonifyURLs=true
locale = 'en-us'
title = "Mad God's Overhaul for Skyrim VR"
theme = 'relearn'
[params]
  themeVariant = 'zen-dark'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false